name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Expo and EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ secrets.GIZLI }}
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create eas.json config
      run: |
        echo '{
          "build": {
            "preview": {
              "android": {
                "buildType": "apk"
              }
            },
            "production": {
              "android": {
                "buildType": "aab"
              }
            }
          }
        }' > eas.json
        
    - name: Build APK
      run: eas build --platform android --profile preview --non-interactive